version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfile.php
    restart: always
    volumes:
      - ./web:/code
    networks:
      - app-network
    

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/code
      - ./www.conf:/etc/nginx/conf.d/www.conf
      - ./admin.conf:/etc/nginx/conf.d/admin.conf
      - ./log:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /var/www/sql_mysql:/var/lib/mysql:rw
      - ./data:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge