version: "3.8"

services:
        database:
                container_name: cup_database
                image: mysql
                restart: always
                environment: 
                - MYSQL_ROOT_PASSWORD= ${MYSQL_PASSWORD}
                - MYSQL_DATABASE= ${MYSQL_DATABASE}
                - MYSQL_USER= ${MYSQL_USER}
                - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
                volumes:
                        - ./data:/docker-entrypoint-initdb.d/
        nginx:
                container_name: cup_nginx
                restart: always
                ports:
                        - 80:80
                build:
                        context: .
                        dockerfile: dockerfile
                volumes:
                        #- ${PWD}/nginx.conf:/etc/nginx/nginx.conf
                        - ./:/code
                links:
                - web-php
        phpmyadmin:
                container_name: cup_phpmyadmin
                image: phpmyadmin/phpmyadmin
                restart: always
                environment:
                - PMA_HOST = ${MYSQL_HOST}
                - PMA_ABSOLUTE_URL = "https://admin.ian-shen.live/phpmyadmin/"
                depends_on:
                - database
                - web-php
                links:
                - web-php
        web-php:
                container_name: php8.1
                image: php:8.1.0-fpm
                restart: always
                volumes:
                        - ./:/code
                        
volumes:
        myapp:

