FROM nginx:latest
WORKDIR /etc/nginx/conf.d/
RUN rm default.conf
COPY ./www.conf ./
COPY ./admin.conf ./
RUN apt-get update
RUN apt-get install -y certbot python3-certbot-nginx
RUN certbot --nginx -n --agree-tos -domains ${ADMIN_URL} -domains ${WWW_URL} -m  ${CERTBOT_EMAIL}  --redirect